Unpublish and delete job posts
desrod/greenhouse pull request #3
Opened 2021-12-02 21:56 UTC by ijansky

The `--reset` flag unpublishes and deletes all job posts that are not on the 'Canonical' or 'INTERNAL' boards, effectively keeping just the templates.

2021-12-12 23:01 UTC, hillpd reviewed
This looks good. Thanks for the contribution! I'll run it through some tests this evening.

2021-12-13 07:20 UTC, hillpd requested changes

2021-12-13 07:32 UTC, hillpd commented
I tested reposting all SEG roles and this worked well.

The only minor issue I noted was that the final job delete was duplicated:
```
Deleting post 'Senior Software Engineer - Linux Engineering (Home based - Americas, Wichita)' from job 1787567 ...
Deleting post 'Senior Software Engineer - Linux Engineering (Home based - Americas, Wichita)' from job 1787567 ...
```

I suspect GH was just slow to remove the final listing after refreshing the page. This makes sense because GH re-orders active jobs ahead of inactive jobs. The final listing doesn't have any active jobs left to mask any delays.

2021-12-13 11:24 UTC, ijansky commented on post-job.py
> +        job_posts = len(wait.until(lambda browser: browser.find_element(By.XPATH, '//*[@id="job_applications"]/tbody/tr')))
Good catch. The method call was replaced by `find_elements()`.

2021-12-13 15:42 UTC, hillpd approved these changes

2021-12-13 16:04 UTC, merged